set_property PACKAGE_PIN Y9 clk
set_property IOSTANDARD LVCMOS33 clk
create_clock -name sys_clk -period 10.0 clk
set_property PACKAGE_PIN AB11 reset
set_property IOSTANDARD LVCMOS33 reset
set_property PACKAGE_PIN V5 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN W5 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN Y5 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AA5 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AB20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AC20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AD20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AE20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AF20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AG20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AH20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AJ20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AK20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AL20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AM20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AN20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AP20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AR20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AT20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AU20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AV20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AW20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN AY20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BA20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BB20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BC20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BD20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BE20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BF20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BG20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BH20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BJ20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BK20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BL20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BM20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BN20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BP20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BQ20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BR20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BS20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BT20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BU20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BV20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BW20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BX20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BY20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN BZ20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CA20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CB20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CC20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CD20 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE13 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE14 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE15 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE16 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE17 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE18 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE19 
set_property IOSTANDARD LVCMOS33 
set_property PACKAGE_PIN CE20 
set_property IOSTANDARD LVCMOS33 
