# ========================================================
# VLIW ASSEMBLY OUTPUT
# Generated by CGRA Compiler Phase 4
# ========================================================
#
# Architecture: 4-way VLIW (4 PEs)
# Instruction Width: 128 bits (32 bits per PE)
# Format: PE0 (LSB) | PE1 | PE2 | PE3 (MSB)
#
# Encoding: RISC-V ISA Standard 32-bit Format
# - Opcode in bits [6:0] (7 bits)
# - Format varies by instruction type (R/I/S/B/U/J)
#

.section .text
.global _start

_start:

    # ==================== CYCLE   0 ==================== (4 ops)
    # PE0: jal ra, 0
    .word 0x000000EF    # PE0 [31:0]
    # PE1: addi a5, a4, 0
    .word 0x00070793    # PE1 [63:32]
    # PE2: bltu zero, zero, 0
    .word 0x00006063    # PE2 [95:64]
    # PE3: bltu zero, zero, 0
    .word 0x00006063    # PE3 [127:96]

    # ==================== CYCLE 001 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 002 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a0, a5, 0
    .word 0x00078513    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 003 ==================== (3 ops)
    # PE0: jalr zero, 0(ra)
    .word 0x00008067    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a5, zero, 4095
    .word 0xFFF00793    # PE2 [95:64]
    # PE3: addi a5, zero, 4095
    .word 0xFFF00793    # PE3 [127:96]

    # ==================== CYCLE 004 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, zero, 2
    .word 0x00200793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 005 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a5, zero, 0
    .word 0x00000793    # PE2 [95:64]
    # PE3: addi a4, zero, 1
    .word 0x00100713    # PE3 [127:96]

    # ==================== CYCLE 006 ==================== (2 ops)
    # PE0: addi a4, zero, 1
    .word 0x00100713    # PE0 [31:0]
    # PE1: addi a5, zero, 4095
    .word 0xFFF00793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 007 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a1, a4, 0
    .word 0x00070593    # PE1 [63:32]
    # PE2: addi a5, zero, 10
    .word 0x00A00793    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 008 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a4, 0
    .word 0x00070793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 009 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a0, a5, 0
    .word 0x00078513    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 010 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a0, a5, 0
    .word 0x00078513    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 011 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a0, 0
    .word 0x00050793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 012 ==================== (2 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: addi a5, a0, 0
    .word 0x00050793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 013 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a0, a5, 0
    .word 0x00078513    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 014 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 015 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a0, 0
    .word 0x00050793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 016 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 017 ==================== (2 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: addi a0, a5, 0
    .word 0x00078513    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 018 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 019 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a0, 0
    .word 0x00050793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 020 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 021 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 022 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 023 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 024 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 025 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 026 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 027 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 028 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 029 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 030 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 031 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 032 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 033 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 034 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 035 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 036 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 037 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 038 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 039 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 040 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 041 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 042 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 043 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 044 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 045 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 046 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 047 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 048 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 049 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 050 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 051 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 052 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 053 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 054 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 055 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 056 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 057 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 058 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 059 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 060 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 061 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 062 ==================== (2 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: sw zero, 0(zero)
    .word 0x00002023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 063 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 064 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 065 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 066 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 067 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 068 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 069 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 070 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 071 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 072 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 073 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 074 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 075 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 076 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 077 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 078 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 079 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 080 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 081 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 082 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 083 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 084 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 085 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 086 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 087 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 088 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 089 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 090 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 091 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 092 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 093 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 094 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 095 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 096 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 097 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 098 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 099 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 100 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 101 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 102 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 103 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 104 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 105 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 106 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 107 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 108 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 109 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 110 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 111 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 112 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 113 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 114 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 115 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 116 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 117 ==================== (2 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: sw zero, 0(zero)
    .word 0x00002023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 118 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 119 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 120 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 121 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 122 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 123 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 124 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 125 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 126 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 127 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 128 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 129 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 130 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 131 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 132 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 133 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 134 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 135 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 136 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 137 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 138 ==================== (2 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: sw zero, 0(zero)
    .word 0x00002023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 139 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 140 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 141 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 142 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 143 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 144 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 145 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 146 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 147 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 148 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 149 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 150 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 151 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 152 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 153 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 154 ==================== (2 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: sw zero, 0(zero)
    .word 0x00002023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 155 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 156 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 157 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 158 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 159 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 160 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 161 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 162 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 163 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 164 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 165 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 166 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 167 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 168 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 169 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 170 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 171 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 172 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 173 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 174 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 175 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 176 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 177 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 178 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 179 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 180 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 181 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 182 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 183 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 184 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 185 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 186 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 187 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 188 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 189 ==================== (1 ops)
    # PE0: sw zero, 0(zero)
    .word 0x00002023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 190 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 191 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 192 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 193 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 194 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 195 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 196 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 197 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 198 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 199 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 200 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 201 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 202 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 203 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 204 ==================== (2 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: sw zero, 0(zero)
    .word 0x00002023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 205 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 206 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 207 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 208 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 209 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: sw zero, 0(zero)
    .word 0x00002023    # PE3 [127:96]

    # ==================== CYCLE 210 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 211 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 212 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 213 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 214 ==================== (3 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: sw zero, 0(zero)
    .word 0x00002023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 215 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 216 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 217 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 218 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 219 ==================== (4 ops)
    # PE0: lw zero, 0(zero)
    .word 0x00002003    # PE0 [31:0]
    # PE1: lw zero, 0(zero)
    .word 0x00002003    # PE1 [63:32]
    # PE2: lw zero, 0(zero)
    .word 0x00002003    # PE2 [95:64]
    # PE3: lw zero, 0(zero)
    .word 0x00002003    # PE3 [127:96]

    # ==================== CYCLE 220 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 221 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP


# ========================================================
# STATISTICS
# ========================================================
# Total Cycles: 222
# Active Cycles: 60
# Total Operations: 140
# Average IPC: 0.63
# Utilization: 15.77%
