# ========================================================
# VLIW ASSEMBLY OUTPUT
# Generated by CGRA Compiler Phase 4
# ========================================================
#
# Architecture: 4-way VLIW (4 PEs)
# Instruction Width: 128 bits (32 bits per PE)
# Format: PE0 (LSB) | PE1 | PE2 | PE3 (MSB)
#
# Encoding: RISC-V ISA Standard 32-bit Format
# - Opcode in bits [6:0] (7 bits)
# - Format varies by instruction type (R/I/S/B/U/J)
#

.section .text
.global _start

_start:

    # ==================== CYCLE   0 ==================== (4 ops)
    # PE0: addi sp, sp, 4032
    .word 0xFC010113    # PE0 [31:0]
    # PE1: lui a5, 65
    .word 0x000417B7    # PE1 [63:32]
    # PE2: addi a5, zero, 9
    .word 0x00900793    # PE2 [95:64]
    # PE3: addi a5, zero, 9
    .word 0x00900793    # PE3 [127:96]

    # ==================== CYCLE 001 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 0
    .word 0x00078793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 002 ==================== (3 ops)
    # PE0: sw s0, 60(sp)
    .word 0x02812E23    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a5, zero, 99
    .word 0x06300793    # PE2 [95:64]
    # PE3: addi a5, zero, 9
    .word 0x00900793    # PE3 [127:96]

    # ==================== CYCLE 003 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 3693
    .word 0xE6D78793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 004 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a5, zero, 29
    .word 0x01D00793    # PE2 [95:64]
    # PE3: addi a5, zero, 99
    .word 0x06300793    # PE3 [127:96]

    # ==================== CYCLE 005 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a3, zero, 0
    .word 0x00000693    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 006 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a4, zero, 0
    .word 0x00000713    # PE2 [95:64]
    # PE3: addi a4, zero, 0
    .word 0x00000713    # PE3 [127:96]

    # ==================== CYCLE 007 ==================== (2 ops)
    # PE0: addi a4, zero, 0
    .word 0x00000713    # PE0 [31:0]
    # PE1: addi a3, zero, 0
    .word 0x00000693    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 008 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a4, zero, 0
    .word 0x00000713    # PE2 [95:64]
    # PE3: addi a4, zero, 0
    .word 0x00000713    # PE3 [127:96]

    # ==================== CYCLE 009 ==================== (2 ops)
    # PE0: addi a5, zero, 0
    .word 0x00000793    # PE0 [31:0]
    # PE1: addi a5, zero, 0
    .word 0x00000793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 010 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a5, zero, 0
    .word 0x00000793    # PE2 [95:64]
    # PE3: addi a5, zero, 0
    .word 0x00000793    # PE3 [127:96]

    # ==================== CYCLE 011 ==================== (2 ops)
    # PE0: addi a5, zero, 0
    .word 0x00000793    # PE0 [31:0]
    # PE1: addi a5, zero, 0
    .word 0x00000793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 012 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a4, zero, 0
    .word 0x00000713    # PE2 [95:64]
    # PE3: addi a5, zero, 0
    .word 0x00000793    # PE3 [127:96]

    # ==================== CYCLE 013 ==================== (2 ops)
    # PE0: addi a5, zero, 0
    .word 0x00000793    # PE0 [31:0]
    # PE1: addi a5, zero, 0
    .word 0x00000793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 014 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: addi a5, zero, 0
    .word 0x00000793    # PE2 [95:64]
    # PE3: addi a5, zero, 0
    .word 0x00000793    # PE3 [127:96]

    # ==================== CYCLE 015 ==================== (2 ops)
    # PE0: addi s0, sp, 64
    .word 0x04010413    # PE0 [31:0]
    # PE1: addi a5, zero, 0
    .word 0x00000793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 016 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 017 ==================== (4 ops)
    # PE0: sw zero, -36(s0)
    .word 0xFC042E23    # PE0 [31:0]
    # PE1: sw a5, -56(s0)
    .word 0xFCF42423    # PE1 [63:32]
    # PE2: sw zero, -24(s0)
    .word 0xFE042423    # PE2 [95:64]
    # PE3: sw zero, -28(s0)
    .word 0xFE042223    # PE3 [127:96]

    # ==================== CYCLE 018 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 019 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 020 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 021 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 022 ==================== (4 ops)
    # PE0: lw a5, 4072(s0)
    .word 0xFE842783    # PE0 [31:0]
    # PE1: lw a5, 4068(s0)
    .word 0xFE442783    # PE1 [63:32]
    # PE2: lw a4, 4060(s0)
    .word 0xFDC42703    # PE2 [95:64]
    # PE3: lw a5, 4072(s0)
    .word 0xFE842783    # PE3 [127:96]

    # ==================== CYCLE 023 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 024 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 025 ==================== (4 ops)
    # PE0: lw a5, 4068(s0)
    .word 0xFE442783    # PE0 [31:0]
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: lw a5, 4072(s0)
    .word 0xFE842783    # PE2 [95:64]
    # PE3: lw a5, 4040(s0)
    .word 0xFC842783    # PE3 [127:96]

    # ==================== CYCLE 026 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 027 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 4068(s0)
    .word 0xFE442703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 028 ==================== (3 ops)
    # PE0: sw a5, -24(s0)
    .word 0xFEF42423    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: sw a5, -56(s0)
    .word 0xFCF42423    # PE2 [95:64]
    # PE3: lw a4, 0(a5)
    .word 0x0007A703    # PE3 [127:96]

    # ==================== CYCLE 029 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 030 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a4, 0
    .word 0x00070793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 031 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: sw zero, -20(s0)
    .word 0xFE042623    # PE3 [127:96]

    # ==================== CYCLE 032 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: slli a5, a5, 2
    .word 0x00279793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 033 ==================== (2 ops)
    # PE0: lw a4, 4072(s0)
    .word 0xFE842703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: lw a5, 4040(s0)
    .word 0xFC842783    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 034 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a5, a4
    .word 0x00E787B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 035 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 036 ==================== (4 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: slli a5, a5, 1
    .word 0x00179793    # PE1 [63:32]
    # PE2: lw a5, 4076(s0)
    .word 0xFEC42783    # PE2 [95:64]
    # PE3: lw a5, 4076(s0)
    .word 0xFEC42783    # PE3 [127:96]

    # ==================== CYCLE 037 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 038 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a4, a5, 0
    .word 0x00078713    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 039 ==================== (3 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: sw a5, -52(s0)
    .word 0xFCF42623    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 040 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a5, a4
    .word 0x00E787B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 041 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: sw a5, -20(s0)
    .word 0xFEF42623    # PE3 [127:96]

    # ==================== CYCLE 042 ==================== (1 ops)
    # PE0: sw a5, -48(s0)
    .word 0xFCF42823    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 043 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 044 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 4044(s0)
    .word 0xFCC42783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 045 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 046 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: lw a4, 4076(s0)
    .word 0xFEC42703    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 047 ==================== (2 ops)
    # PE0: sw a5, -52(s0)
    .word 0xFCF42623    # PE0 [31:0]
    # PE1: mul a4, a4, a5
    .word 0x02F70733    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 048 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 049 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: bge a5, a4, 0
    .word 0x00E7D063    # PE2 [95:64]
    # PE3: sw zero, -20(s0)
    .word 0xFE042623    # PE3 [127:96]

    # ==================== CYCLE 050 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: slli a5, a5, 2
    .word 0x00279793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 051 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a4, a4, a5
    .word 0x00F70733    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 052 ==================== (2 ops)
    # PE0: lw a5, 4044(s0)
    .word 0xFCC42783    # PE0 [31:0]
    # PE1: add a5, a3, a5
    .word 0x00F687B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 053 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: sw a4, 0(a5)
    .word 0x00E7A023    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 054 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: lw a5, 4076(s0)
    .word 0xFEC42783    # PE3 [127:96]

    # ==================== CYCLE 055 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 056 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 057 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 058 ==================== (2 ops)
    # PE0: lw a5, 0(a5)
    .word 0x0007A783    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: lw a5, 0(a5)
    .word 0x0007A783    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 059 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: sw a5, -20(s0)
    .word 0xFEF42623    # PE3 [127:96]

    # ==================== CYCLE 060 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 061 ==================== (2 ops)
    # PE0: bge a5, zero, 0
    .word 0x0007D063    # PE0 [31:0]
    # PE1: sub a4, zero, a5
    .word 0x40F00733    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 062 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 063 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: sw a4, 0(a5)
    .word 0x00E7A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 064 ==================== (1 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 065 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 066 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 067 ==================== (2 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: sw zero, -20(s0)
    .word 0xFE042623    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 068 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 0(a5)
    .word 0x0007A783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 069 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 070 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 071 ==================== (1 ops)
    # PE0: sw a5, -32(s0)
    .word 0xFEF42023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 072 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: lw a5, 4076(s0)
    .word 0xFEC42783    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 073 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 074 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 075 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 076 ==================== (1 ops)
    # PE0: lw a5, 4064(s0)
    .word 0xFE042783    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 077 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: sw a5, -20(s0)
    .word 0xFEF42623    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 078 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 079 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 4066
    .word 0xFE278793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 080 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 081 ==================== (1 ops)
    # PE0: sw a5, -32(s0)
    .word 0xFEF42023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 082 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 4076(s0)
    .word 0xFEC42703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 083 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 084 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 085 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: bge a5, a4, 0
    .word 0x00E7D063    # PE1 [63:32]
    # PE2: sw zero, -20(s0)
    .word 0xFE042623    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 086 ==================== (2 ops)
    # PE0: lw a4, 4064(s0)
    .word 0xFE042703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: lw a4, 4064(s0)
    .word 0xFE042703    # PE3 [127:96]

    # ==================== CYCLE 087 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 088 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 089 ==================== (2 ops)
    # PE0: blt a5, a4, 0
    .word 0x00E7C063    # PE0 [31:0]
    # PE1: sw a4, 0(a5)
    .word 0x00E7A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 090 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: lw a5, 4076(s0)
    .word 0xFEC42783    # PE2 [95:64]
    # PE3: lw a4, 4076(s0)
    .word 0xFEC42703    # PE3 [127:96]

    # ==================== CYCLE 091 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 092 ==================== (1 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 093 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a4, 0
    .word 0x00070793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 094 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: lw a4, 0(a5)
    .word 0x0007A703    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 095 ==================== (2 ops)
    # PE0: sw a5, -20(s0)
    .word 0xFEF42623    # PE0 [31:0]
    # PE1: addi a5, a4, 0
    .word 0x00070793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 096 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 097 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: mul a4, a4, a5
    .word 0x02F70733    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 098 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 099 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a5, a4
    .word 0x00E787B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 100 ==================== (1 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 101 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a4, a4, a5
    .word 0x00F70733    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 102 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 103 ==================== (4 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: addi a4, a5, 0
    .word 0x00078713    # PE1 [63:32]
    # PE2: sw zero, -20(s0)
    .word 0xFE042623    # PE2 [95:64]
    # PE3: sw a4, 0(a5)
    .word 0x00E7A023    # PE3 [127:96]

    # ==================== CYCLE 104 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 105 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a5, a4
    .word 0x00E787B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 106 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 107 ==================== (1 ops)
    # PE0: sw a5, -44(s0)
    .word 0xFCF42A23    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 108 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: lw a5, 4076(s0)
    .word 0xFEC42783    # PE2 [95:64]
    # PE3: lw a5, 4076(s0)
    .word 0xFEC42783    # PE3 [127:96]

    # ==================== CYCLE 109 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 110 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 111 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: lw a5, 4056(s0)
    .word 0xFD842783    # PE2 [95:64]
    # PE3: lw a5, 0(a5)
    .word 0x0007A783    # PE3 [127:96]

    # ==================== CYCLE 112 ==================== (1 ops)
    # PE0: lw a5, 4052(s0)
    .word 0xFD442783    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 113 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 114 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: slli a5, a5, 2
    .word 0x00279793    # PE1 [63:32]
    # PE2: bge a5, zero, 0
    .word 0x0007D063    # PE2 [95:64]
    # PE3: sw a5, -20(s0)
    .word 0xFEF42623    # PE3 [127:96]

    # ==================== CYCLE 115 ==================== (2 ops)
    # PE0: lw a5, 0(a5)
    .word 0x0007A783    # PE0 [31:0]
    # PE1: slli a5, a5, 2
    .word 0x00279793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 116 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 117 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 118 ==================== (1 ops)
    # PE0: sub a4, zero, a5
    .word 0x40F00733    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 119 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 4076(s0)
    .word 0xFEC42703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 120 ==================== (1 ops)
    # PE0: sw a4, 0(a5)
    .word 0x00E7A023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 121 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 122 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: bge a5, a4, 0
    .word 0x00E7D063    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 123 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 124 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 125 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 0(a5)
    .word 0x0007A783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 126 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 127 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 128 ==================== (1 ops)
    # PE0: sw a5, -32(s0)
    .word 0xFEF42023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 129 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 130 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 131 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 132 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 133 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a5, 4064(s0)
    .word 0xFE042783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 134 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 135 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 136 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 4066
    .word 0xFE278793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 137 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 138 ==================== (1 ops)
    # PE0: sw a5, -32(s0)
    .word 0xFEF42023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 139 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 140 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 141 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 142 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 143 ==================== (2 ops)
    # PE0: lw a4, 4064(s0)
    .word 0xFE042703    # PE0 [31:0]
    # PE1: lw a4, 4064(s0)
    .word 0xFE042703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 144 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 145 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 146 ==================== (2 ops)
    # PE0: blt a5, a4, 0
    .word 0x00E7C063    # PE0 [31:0]
    # PE1: sw a4, 0(a5)
    .word 0x00E7A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 147 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 148 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 149 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 150 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 151 ==================== (1 ops)
    # PE0: sw zero, 0(a5)
    .word 0x0007A023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 152 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 153 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 154 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 155 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 156 ==================== (2 ops)
    # PE0: lw a4, 0(a5)
    .word 0x0007A703    # PE0 [31:0]
    # PE1: lw a5, 0(a5)
    .word 0x0007A783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 157 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 158 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 159 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: mul a5, a4, a5
    .word 0x02F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 160 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 161 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 162 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 163 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 164 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 165 ==================== (1 ops)
    # PE0: sw a5, -36(s0)
    .word 0xFCF42E23    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 166 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 167 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 168 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 169 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 170 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 4060(s0)
    .word 0xFDC42703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 171 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 172 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 173 ==================== (1 ops)
    # PE0: sw a4, 0(a5)
    .word 0x00E7A023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 174 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 175 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 176 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 177 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 178 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 0(a5)
    .word 0x0007A703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 179 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 180 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 181 ==================== (1 ops)
    # PE0: sw a4, 0(a5)
    .word 0x00E7A023    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 182 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 183 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 184 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 185 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP


# ========================================================
# STATISTICS
# ========================================================
# Total Cycles: 186
# Active Cycles: 100
# Total Operations: 162
# Average IPC: 0.87
# Utilization: 21.77%
