# ========================================================
# VLIW ASSEMBLY OUTPUT
# Generated by CGRA Compiler Phase 4
# ========================================================
#
# Architecture: 4-way VLIW (4 PEs)
# Instruction Width: 128 bits (32 bits per PE)
# Format: PE0 (LSB) | PE1 | PE2 | PE3 (MSB)
#
# Encoding: RISC-V ISA Standard 32-bit Format
# - Opcode in bits [6:0] (7 bits)
# - Format varies by instruction type (R/I/S/B/U/J)
#

.section .text
.global _start

_start:

    # ==================== CYCLE   0 ==================== (4 ops)
    # PE0: addi sp, sp, 4064
    .word 0xFE010113    # PE0 [31:0]
    # PE1: addi a5, zero, 99
    .word 0x06300793    # PE1 [63:32]
    # PE2: addi a5, zero, 99
    .word 0x06300793    # PE2 [95:64]
    # PE3: addi a5, zero, 99
    .word 0x06300793    # PE3 [127:96]

    # ==================== CYCLE 001 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 002 ==================== (4 ops)
    # PE0: sw s0, 28(sp)
    .word 0x00812E23    # PE0 [31:0]
    # PE1: addi a5, zero, 99
    .word 0x06300793    # PE1 [63:32]
    # PE2: addi a5, zero, 99
    .word 0x06300793    # PE2 [95:64]
    # PE3: addi a3, zero, 0
    .word 0x00000693    # PE3 [127:96]

    # ==================== CYCLE 003 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 004 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a4, zero, 0
    .word 0x00000713    # PE1 [63:32]
    # PE2: addi a3, zero, 0
    .word 0x00000693    # PE2 [95:64]
    # PE3: addi a4, zero, 0
    .word 0x00000713    # PE3 [127:96]

    # ==================== CYCLE 005 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 006 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a3, zero, 0
    .word 0x00000693    # PE1 [63:32]
    # PE2: addi a4, zero, 0
    .word 0x00000713    # PE2 [95:64]
    # PE3: addi a4, zero, 1
    .word 0x00100713    # PE3 [127:96]

    # ==================== CYCLE 007 ==================== (1 ops)
    # PE0: addi a4, zero, 0
    .word 0x00000713    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 008 ==================== (3 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a4, zero, 1
    .word 0x00100713    # PE1 [63:32]
    # PE2: addi a4, zero, 0
    .word 0x00000713    # PE2 [95:64]
    # PE3: addi s0, sp, 32
    .word 0x02010413    # PE3 [127:96]

    # ==================== CYCLE 009 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 010 ==================== (1 ops)
    # PE0: sw zero, -20(s0)
    .word 0xFE042623    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 011 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 012 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 013 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 014 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 015 ==================== (2 ops)
    # PE0: lw a5, 4076(s0)
    .word 0xFEC42783    # PE0 [31:0]
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 016 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 017 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 018 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 019 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 020 ==================== (2 ops)
    # PE0: sw a5, -20(s0)
    .word 0xFEF42623    # PE0 [31:0]
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 021 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 022 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: sw a4, 0(a5)
    .word 0x00E7A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 023 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 024 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 025 ==================== (1 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 026 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 027 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 028 ==================== (2 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: sw zero, -20(s0)
    .word 0xFE042623    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 029 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 030 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 031 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 032 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 033 ==================== (2 ops)
    # PE0: lw a5, 4076(s0)
    .word 0xFEC42783    # PE0 [31:0]
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 034 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 035 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 036 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 037 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 038 ==================== (2 ops)
    # PE0: sw a5, -20(s0)
    .word 0xFEF42623    # PE0 [31:0]
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 039 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 040 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: sw a4, 0(a5)
    .word 0x00E7A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 041 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 042 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 043 ==================== (1 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 044 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 045 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 046 ==================== (2 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: sw zero, -20(s0)
    .word 0xFE042623    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 047 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 048 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 049 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 050 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 051 ==================== (2 ops)
    # PE0: lw a5, 4076(s0)
    .word 0xFEC42783    # PE0 [31:0]
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 052 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 053 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 054 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 055 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 056 ==================== (2 ops)
    # PE0: sw a5, -20(s0)
    .word 0xFEF42623    # PE0 [31:0]
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 057 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 058 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: sw zero, 0(a5)
    .word 0x0007A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 059 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 060 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 061 ==================== (1 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 062 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 063 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 064 ==================== (2 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: sw zero, -20(s0)
    .word 0xFE042623    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 065 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 066 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 067 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 068 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 069 ==================== (4 ops)
    # PE0: lw a5, 4076(s0)
    .word 0xFEC42783    # PE0 [31:0]
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: lw a5, 4076(s0)
    .word 0xFEC42783    # PE2 [95:64]
    # PE3: lw a5, 4076(s0)
    .word 0xFEC42783    # PE3 [127:96]

    # ==================== CYCLE 070 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 071 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 072 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 073 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 074 ==================== (2 ops)
    # PE0: sw a5, -20(s0)
    .word 0xFEF42623    # PE0 [31:0]
    # PE1: add a5, a3, a5
    .word 0x00F687B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 075 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 076 ==================== (2 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 0(a5)
    .word 0x0007A703    # PE1 [63:32]
    # PE2: lw a5, 0(a5)
    .word 0x0007A783    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 077 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 078 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 079 ==================== (2 ops)
    # PE0: lw a4, 4076(s0)
    .word 0xFEC42703    # PE0 [31:0]
    # PE1: add a4, a4, a5
    .word 0x00F70733    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 080 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 081 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: sw a4, 0(a5)
    .word 0x00E7A023    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 082 ==================== (2 ops)
    # PE0: bge a5, a4, 0
    .word 0x00E7D063    # PE0 [31:0]
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: sw zero, -20(s0)
    .word 0xFE042623    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 083 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 084 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 085 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 086 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 087 ==================== (3 ops)
    # PE0: lw a5, 4076(s0)
    .word 0xFEC42783    # PE0 [31:0]
    # PE1: lw a5, 4076(s0)
    .word 0xFEC42783    # PE1 [63:32]
    # PE2: lw a5, 4076(s0)
    .word 0xFEC42783    # PE2 [95:64]
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 088 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 089 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 090 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: addi a5, a5, 1
    .word 0x00178793    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 091 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 092 ==================== (2 ops)
    # PE0: sw a5, -20(s0)
    .word 0xFEF42623    # PE0 [31:0]
    # PE1: add a5, a4, a5
    .word 0x00F707B3    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 093 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 094 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: lw a4, 0(a5)
    .word 0x0007A703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 095 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 096 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 097 ==================== (2 ops)
    # PE0: sw a4, 0(a5)
    .word 0x00E7A023    # PE0 [31:0]
    # PE1: lw a4, 4076(s0)
    .word 0xFEC42703    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 098 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 099 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 100 ==================== (1 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: bge a5, a4, 0
    .word 0x00E7D063    # PE1 [63:32]
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 101 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP

    # ==================== CYCLE 102 ==================== (0 ops)
    # PE0: nop
    .word 0x00000000    # PE0 [31:0] - NOP
    # PE1: nop
    .word 0x00000000    # PE1 [63:32] - NOP
    # PE2: nop
    .word 0x00000000    # PE2 [95:64] - NOP
    # PE3: nop
    .word 0x00000000    # PE3 [127:96] - NOP


# ========================================================
# STATISTICS
# ========================================================
# Total Cycles: 103
# Active Cycles: 38
# Total Operations: 70
# Average IPC: 0.68
# Utilization: 16.99%
