#!/usr/bin/env python3
"""
RISC-V Assembly Normalizer for CGRA ISA
"""

import sys
import re

class AsmNormalizer:
    def __init__(self):
        self.supported_instructions = {
            'add', 'sub', 'mul', 'and', 'or', 'xor', 
            'sll', 'srl', 'sra', 'slt', 'sltu',
            'addi', 'slti', 'sltiu', 'xori', 'ori', 'andi',
            'slli', 'srli', 'srai',
            'lw', 'lh', 'lhu', 'lb', 'lbu',
            'jalr',
            'sw', 'sh', 'sb',
            'beq', 'bne', 'blt', 'bge', 'bltu', 'bgeu',
            'jal',
            'lui', 'auipc'
        }
        
        self.keep_directives = {'.text', '.data', '.bss'}
        self.remove_directives = {
            '.file', '.option', '.attribute', '.ident',
            '.section', '.globl', '.global', '.type', '.size',
            '.align', '.p2align', '.balign',
            '.comm', '.common', '.local',
            '.weak', '.hidden', '.protected'
        }
        
        self.unsupported_instructions = []
        self.has_errors = False
        self.pseudo_instruction_map = {}  # Maps line_num -> original pseudo instruction
        
        # Instructions that come from specific C operations
        self.c_operation_map = {
            'rem': 'modulo operator (%)',
            'remu': 'modulo operator (%) with unsigned operands',
            'div': 'division operator (/)',
            'divu': 'division operator (/) with unsigned operands',
            'mulh': 'multiplication with high bits (overflow handling)',
            'mulhsu': 'multiplication with high bits (signed x unsigned)',
            'mulhu': 'multiplication with high bits (unsigned)'
        }
    
    def normalize_file(self, input_path, output_path):
        try:
            with open(input_path, 'r') as f:
                lines = f.readlines()
            
            normalized_lines = []
            for i, line in enumerate(lines, 1):
                expanded = self.normalize_line(line, i, pseudo_origin=None)
                normalized_lines.extend(expanded)
            
            # Check if there were unsupported instructions
            if self.has_errors:
                print("\n" + "="*70)
                print("[ERROR] NORMALIZATION FAILED - UNSUPPORTED INSTRUCTIONS DETECTED")
                print("="*70)
                print(f"\nFound {len(self.unsupported_instructions)} unsupported instruction(s):\n")
                
                for line_num, opcode, full_line, original_pseudo in self.unsupported_instructions:
                    print(f"  Line {line_num}: Unsupported instruction '{opcode}'")
                    print(f"    Code: {full_line.strip()}")
                    
                    # Check if this instruction comes from a known C operation
                    if opcode in self.c_operation_map:
                        print(f"    Origin: Generated by C {self.c_operation_map[opcode]}")
                        print(f"    Note: The CGRA does not support hardware division/modulo")
                    elif original_pseudo:
                        print(f"    Origin: Expanded from pseudo-instruction '{original_pseudo}'")
                    print()
                
                print("These instructions are NOT supported by the CGRA ISA.")
                print("\nSupported instructions are:")
                print("  Arithmetic: add, sub, mul")
                print("  Logical: and, or, xor, sll, srl, sra")
                print("  Comparison: slt, sltu")
                print("  Immediate: addi, slti, sltiu, xori, ori, andi")
                print("  Shift Immediate: slli, srli, srai")
                print("  Load: lw, lh, lhu, lb, lbu")
                print("  Store: sw, sh, sb")
                print("  Branch: beq, bne, blt, bge, bltu, bgeu")
                print("  Jump: jal, jalr")
                print("  Upper Immediate: lui, auipc")
                print("\n" + "="*70)
                print("[ERROR] OUTPUT FILE NOT GENERATED")
                print("="*70 + "\n")
                sys.exit(1)
            
            with open(output_path, 'w') as f:
                f.write('\n'.join(normalized_lines))
            
            print(f"[OK] Normalized: {input_path} -> {output_path}")
            print(f"     Lines: {len(lines)} -> {len(normalized_lines)}")
            
        except Exception as e:
            print(f"[ERROR] Error: {e}")
            sys.exit(1)
    
    def normalize_line(self, line, line_num, pseudo_origin=None):
        original = line.rstrip()
        stripped = original.lstrip()
        
        # Comments
        if not stripped or stripped.startswith('#'):
            return [original]
        
        # Split code and comment
        if '#' in line:
            code, comment = line.split('#', 1)
            code = code.rstrip()
            comment = ' #' + comment
        else:
            code = line.rstrip()
            comment = ''
        
        # Labels
        if code.strip().endswith(':'):
            label = code.strip()
            if '@' in label:
                label = label.split('@')[0].strip()
            return [label]
        
        # Directives
        if code.strip().startswith('.'):
            directive = code.strip().split()[0] if code.strip().split() else ''
            if directive in self.keep_directives:
                return [code]
            if directive in self.remove_directives or directive.startswith('.note'):
                return []
            if directive in {'.word', '.string', '.ascii', '.asciz', '.byte', '.half', '.space'}:
                return [code]
            return []
        
        # Instructions
        tokens = code.strip().split(None, 1)  # Split only on first whitespace
        if not tokens:
            return []
        
        opcode = tokens[0].lower()
        operands = tokens[1] if len(tokens) > 1 else ''
        
        # Expand pseudo-instructions
        expanded = self.expand_pseudo(opcode, operands, comment, line_num)
        if expanded is not None:
            # Store the original pseudo-instruction for backtracking
            original_pseudo = f"{opcode} {operands}".strip()
            self.pseudo_instruction_map[line_num] = original_pseudo
            return expanded
        
        # Check supported
        if opcode not in self.supported_instructions:
            # Get the original pseudo-instruction if it exists
            origin = self.pseudo_instruction_map.get(line_num, pseudo_origin)
            self.unsupported_instructions.append((line_num, opcode, code.strip(), origin))
            self.has_errors = True
            return []
        
        # Return formatted line
        return [f'\t{opcode} {operands}{comment}']
    
    def expand_pseudo(self, opcode, operands, comment, line_num):
        ops = [o.strip() for o in operands.split(',')]
        
        # nop
        if opcode == 'nop':
            return [f'\taddi zero, zero, 0{comment or " # nop"}']
        
        # mv rd, rs
        if opcode == 'mv' and len(ops) == 2:
            return [f'\taddi {ops[0]}, {ops[1]}, 0{comment or f" # mv {ops[0]}, {ops[1]}"}']
        
        # li rd, imm
        if opcode == 'li' and len(ops) == 2:
            try:
                imm = self.parse_imm(ops[1])
                if -2048 <= imm <= 2047:
                    return [f'\taddi {ops[0]}, zero, {imm}{comment or f" # li {ops[0]}, {imm}"}']
                else:
                    upper = (imm + 0x800) >> 12
                    lower = imm & 0xfff
                    if lower >= 2048:
                        lower -= 4096
                    return [
                        f'\tlui {ops[0]}, {upper & 0xFFFFF} # li {ops[0]}, {imm}',
                        f'\taddi {ops[0]}, {ops[0]}, {lower}{comment}'
                    ]
            except:
                original_pseudo = f"li {ops[0]}, {ops[1]}"
                self.unsupported_instructions.append((line_num, 'li (invalid immediate)', operands, original_pseudo))
                self.has_errors = True
                return []
        
        # lla/la rd, symbol -> addi rd, zero, 0 (placeholder)
        if opcode in ['lla', 'la'] and len(ops) == 2:
            return [f'\taddi {ops[0]}, zero, 0 # {opcode} {ops[0]}, {ops[1]} (unresolved){comment}']
        
        # not rd, rs
        if opcode == 'not' and len(ops) == 2:
            return [f'\txori {ops[0]}, {ops[1]}, -1{comment or f" # not {ops[0]}, {ops[1]}"}']
        
        # neg rd, rs
        if opcode == 'neg' and len(ops) == 2:
            return [f'\tsub {ops[0]}, zero, {ops[1]}{comment or f" # neg {ops[0]}, {ops[1]}"}']
        
        # seqz rd, rs
        if opcode == 'seqz' and len(ops) == 2:
            return [f'\tsltiu {ops[0]}, {ops[1]}, 1{comment or f" # seqz {ops[0]}, {ops[1]}"}']
        
        # snez rd, rs
        if opcode == 'snez' and len(ops) == 2:
            return [f'\tsltu {ops[0]}, zero, {ops[1]}{comment or f" # snez {ops[0]}, {ops[1]}"}']
        
        # Branches
        if opcode == 'beqz' and len(ops) == 2:
            return [f'\tbeq {ops[0]}, zero, {ops[1]}{comment or f" # beqz {ops[0]}, {ops[1]}"}']
        
        if opcode == 'bnez' and len(ops) == 2:
            return [f'\tbne {ops[0]}, zero, {ops[1]}{comment or f" # bnez {ops[0]}, {ops[1]}"}']
        
        if opcode == 'blez' and len(ops) == 2:
            return [f'\tbge zero, {ops[0]}, {ops[1]}{comment or f" # blez {ops[0]}, {ops[1]}"}']
        
        if opcode == 'bgez' and len(ops) == 2:
            return [f'\tbge {ops[0]}, zero, {ops[1]}{comment or f" # bgez {ops[0]}, {ops[1]}"}']
        
        if opcode == 'bltz' and len(ops) == 2:
            return [f'\tblt {ops[0]}, zero, {ops[1]}{comment or f" # bltz {ops[0]}, {ops[1]}"}']
        
        if opcode == 'bgtz' and len(ops) == 2:
            return [f'\tblt zero, {ops[0]}, {ops[1]}{comment or f" # bgtz {ops[0]}, {ops[1]}"}']
        
        if opcode == 'bgt' and len(ops) == 3:
            return [f'\tblt {ops[1]}, {ops[0]}, {ops[2]}{comment or f" # bgt {ops[0]}, {ops[1]}, {ops[2]}"}']
        
        if opcode == 'ble' and len(ops) == 3:
            return [f'\tbge {ops[1]}, {ops[0]}, {ops[2]}{comment or f" # ble {ops[0]}, {ops[1]}, {ops[2]}"}']
        
        if opcode == 'bgtu' and len(ops) == 3:
            return [f'\tbltu {ops[1]}, {ops[0]}, {ops[2]}{comment or f" # bgtu {ops[0]}, {ops[1]}, {ops[2]}"}']
        
        if opcode == 'bleu' and len(ops) == 3:
            return [f'\tbgeu {ops[1]}, {ops[0]}, {ops[2]}{comment or f" # bleu {ops[0]}, {ops[1]}, {ops[2]}"}']
        
        # Jumps
        if opcode == 'j' and len(ops) == 1:
            return [f'\tjal zero, {ops[0]}{comment or f" # j {ops[0]}"}']
        
        if opcode == 'jr' and len(ops) == 1:
            return [f'\tjalr zero, {ops[0]}, 0{comment or f" # jr {ops[0]}"}']
        
        if opcode == 'ret':
            return [f'\tjalr zero, ra, 0{comment or " # ret"}']
        
        if opcode == 'call' and len(ops) == 1:
            return [f'\tjal ra, {ops[0]}{comment or f" # call {ops[0]}"}']
        
        if opcode == 'tail' and len(ops) == 1:
            return [f'\tjal zero, {ops[0]}{comment or f" # tail {ops[0]}"}']
        
        return None
    
    def parse_imm(self, imm_str):
        imm_str = imm_str.strip().strip(',')
        if imm_str.startswith('0x') or imm_str.startswith('0X'):
            return int(imm_str, 16)
        if imm_str.startswith('0b') or imm_str.startswith('0B'):
            return int(imm_str, 2)
        if imm_str.startswith('0') and len(imm_str) > 1 and imm_str[1].isdigit():
            return int(imm_str, 8)
        return int(imm_str)

def main():
    if len(sys.argv) != 3:
        print("Usage: python asm_normalizer.py <input.s> <output.s>")
        sys.exit(1)
    
    normalizer = AsmNormalizer()
    normalizer.normalize_file(sys.argv[1], sys.argv[2])

if __name__ == '__main__':
    main()